# FILE: .github/workflows/deploy.yml

name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository yuklash
        uses: actions/checkout@v3

      - name: Flutter oâ€˜rnatish
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.0
          channel: stable

      - name: Dependenciyalarni yuklash
        run: flutter pub get

      - name: Web build qilish
        run: |
          flutter build web \
          --release \
          --base-href "/checkepr/" \
          --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
          --dart-define=SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}

      - name: GitHub Pages ga deploy qilish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web